name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test-linux-jtreg:
    name: "Linux run.sh"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 25
        include:
          - jdkconf: JDK 25
            jdkver: "25"
            osver: "10"
            jdkimage: "docker.io/library/eclipse-temurin:25-jdk-ubi10-minimal"
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install podman git
      - name: Versions
        run: |
          podman --version
          podman run --rm  -it ${{matrix.jdkimage}} bash --version
          podman run --rm  -it ${{matrix.jdkimage}} java --version
          podman run --rm  -it ${{matrix.jdkimage}} cat /etc/redhat-release
      - name: RFaS
        run:  |
          ls -l
          git submodule update --init --recursive --rebase --force
          ls -l run-folder-as-tests
          a=$(ls run-folder-as-tests | wc -l)
          echo "total $a"
          test $a -gt 3
      - name: Run
        run: |
          CQA_FAIL=false BLACKLIST="101.*" RFAT_RERUNS=2 bash ./run_containerqa.sh  --container-image=${{matrix.jdkimage}}
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: "linux-jtreg-jdk${{ matrix.jdkver}}"
          path: "test.*.tar.gz"

